#!/usr/bin/expect
spawn "stop-yarn.sh"
expect "bluemoon@localhost" { send "1234lol\r" }
interact
spawn "stop-dfs.sh"
expect "bluemoon@localhost" { send "1234lol\r" }
expect "bluemoon@localhost" { send "1234lol\r" }
expect "bluemoon@0.0.0.0" { send "1234lol\r" }
interact
